name: Deploy Backend to cloudtype
on:
  push:
    branches:
      - main
    paths:
      - 'solarloop-ai/backend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: pyoseonchoi/huss_hackerton
          stage: main
          yaml: |
            name: huss-hackerton
            app: python@3.11
            options:
              env: []
              buildenv: []
              start: uvicorn app.main:app --host 0.0.0.0 --port 8000
              ports: "8000"
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
                path: solarloop-ai/backend
